class LeanError(Exception):
    pass


class ReplError(Exception):
    pass
